version: '3'
services:
  orderly_server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    container_name: orderly_server

  orderly_client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: orderly_client
