version: '3'
services:
  orderly_server:
    build:
      context: ./server
    ports:
      - "8001:8001"
    container_name: orderly_server

  orderly_client:
    build:
      context: ./client
    ports:
      - "3001:3001"
    container_name: orderly_client
